-- Create a table for public profiles using the auth.users table
create table public.profiles (
  id uuid not null references auth.users on delete cascade,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,

  primary key (id),
  unique(username),
  constraint username_length check (char_length(username) >= 3)
);

alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create a table for saved recipes (Likes/Bookmarks)
create table public.saved_recipes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  recipe_id bigint references public.recipes not null,
  
  unique(user_id, recipe_id)
);

alter table public.saved_recipes enable row level security;

create policy "Users can view their own saved recipes."
  on saved_recipes for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own saved recipes."
  on saved_recipes for insert
  with check ( auth.uid() = user_id );

create policy "Users can delete their own saved recipes."
  on saved_recipes for delete
  using ( auth.uid() = user_id );

-- Set up Realtime for saved_recipes (optional, but good for instant UI updates)
alter publication supabase_realtime add table saved_recipes;
