-- Create shopping_items table
create table public.shopping_items (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  ingredient text not null,
  recipe_id bigint references public.recipes(id),
  is_checked boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies
alter table public.shopping_items enable row level security;

create policy "Users can view their own shopping items"
  on public.shopping_items for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own shopping items"
  on public.shopping_items for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own shopping items"
  on public.shopping_items for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own shopping items"
  on public.shopping_items for delete
  using ( auth.uid() = user_id );

-- Enable Realtime
alter publication supabase_realtime add table public.shopping_items;
