-- Enterprise Grade Analytics Migration
-- Optimized for High-Volume Ingestion and Flexible Querying

-- 1. Create the main analytics table (Partitioned by Month for Scalability)
CREATE TABLE IF NOT EXISTS analytics_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    event_type TEXT NOT NULL,          -- e.g., 'order_click', 'page_view', 'share'
    channel TEXT,                      -- e.g., 'whatsapp', 'sms', 'instagram'
    entity_id TEXT,                    -- e.g., 'recipe-slug-123'
    user_id UUID,                      -- Optional: Link to auth.users if logged in
    session_id TEXT,                   -- For tracking anonymous flows
    metadata JSONB DEFAULT '{}'::JSONB, -- Flexible: { sku, price, referrer, device_type }
    
    PRIMARY KEY (id, created_at)       -- Required for time-partitioning
) PARTITION BY RANGE (created_at);

-- 2. Create Partitions (Next 12 Months)
CREATE TABLE IF NOT EXISTS analytics_events_2025_12 PARTITION OF analytics_events
    FOR VALUES FROM ('2025-12-01') TO ('2026-01-01');
    
CREATE TABLE IF NOT EXISTS analytics_events_2026_01 PARTITION OF analytics_events
    FOR VALUES FROM ('2026-01-01') TO ('2026-02-01');

CREATE TABLE IF NOT EXISTS analytics_events_default PARTITION OF analytics_events DEFAULT;

-- 3. High-Performance Indexes
-- Time-Series Charting: Fast retrieval by date
CREATE INDEX IF NOT EXISTS idx_analytics_created_at ON analytics_events (created_at DESC);

-- Filtering: Fast filtering by type and channel
CREATE INDEX IF NOT EXISTS idx_analytics_type_channel ON analytics_events (event_type, channel);

-- JSONB Indexing: Ultra-fast querying inside the JSON blob (e.g. find all clicks where sku='gold-plan')
CREATE INDEX IF NOT EXISTS idx_analytics_metadata ON analytics_events USING GIN (metadata);

-- 4. Security (RLS)
ALTER TABLE analytics_events ENABLE ROW LEVEL SECURITY;

-- Block Public viewing (Only internal dashboards/service role can read)
CREATE POLICY "Service Role Full Access" ON analytics_events
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- Allow Authenticated Users to Insert (if we move to client-side analytics later)
-- For now, we only trust the Server (Service Role), so no public policy.

COMMENT ON TABLE analytics_events IS 'Central repository for high-volume application telemetry.';
